[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
optimizer=true
optimizer_runs=200
evm_version="cancun"
solc_version="0.8.30"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet="${MAINNET_RPC_URL}"
sepolia="${SEPOLIA_RPC_URL}"